'use client';
import Header from '@components/header';
import LayoutLayer from '@components/layout-layer';
import Signup from '@components/signup';
// import type { Metadata } from "next";
import '@styles/globals.css';
import { Sign } from 'crypto';
import { useEffect, useState } from 'react';
import { Provider } from 'react-redux';
import store from 'redux/store';

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const [isClient, setIsClient] = useState(false);
    const [isOpen, setIsOpen] = useState(false);

    const toggleModal = () => {
        console.log('clicked');
        setIsOpen(!isOpen);
    };
    useEffect(() => {
        setIsClient(true);
    }, []);

    if (!isClient) {
        return null; // or a loading spinner
    }

    return (
        <html lang="en">
            <body>
                <Provider store={store}>
                    <LayoutLayer>
                        <Header isOpen={isOpen} toggleModal={toggleModal} />
                        {isOpen && <Signup toggleModal={toggleModal} />}
                        <main>{children}</main>
                    </LayoutLayer>
                </Provider>
            </body>
        </html>
    );
}
