"use client";
import Header from "@components/header";
import LayoutLayer from "@components/layout-layer";
// import type { Metadata } from "next";
import "@styles/globals.css";
import { useEffect, useState } from "react";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(true);
  }, []);

  if (!isClient) {
    return null; // or a loading spinner
  }

  return (
    <html lang="en">
      <body>
        <LayoutLayer>
          <Header />
          <main>{children}</main>
        </LayoutLayer>
      </body>
    </html>
  );
}
